TRUNCATE TABLE notefinal RESTART IDENTITY CASCADE;
TRUNCATE TABLE note RESTART IDENTITY CASCADE;
TRUNCATE TABLE parametre RESTART IDENTITY CASCADE;
TRUNCATE TABLE operateur RESTART IDENTITY CASCADE;
TRUNCATE TABLE resolution RESTART IDENTITY CASCADE;
TRUNCATE TABLE candidat RESTART IDENTITY CASCADE;
TRUNCATE TABLE matiere RESTART IDENTITY CASCADE;
TRUNCATE TABLE correcteur RESTART IDENTITY CASCADE;